{% set name = "influxdb-client" %}
{% set version = "1.39.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/influxdb_client-{{ version }}.tar.gz
  sha256: 6a534913523bd262f1928e4ff80046bf95e313c1694ce13e45fd17eea90fe691

build:
  number: 0
  noarch: python

  # noarch: only build on linux64
  skip: true # [not linux64]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
    - wheel
  run:
    - python >=3.7
    - reactivex >=4.0.4
    - certifi >=14.05.14
    - python-dateutil >=2.5.3
    - setuptools >=21.0.0
    - urllib3 >=1.26.0

test:
  imports:
    - influxdb_client
    - influxdb_client.client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/influxdata/influxdb-client-python
  summary: InfluxDB 2.0 Python client library
  license: MIT
  license_file: LICENSE

extra:
  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url
    - avoid_noarch

    - missing_license_family
    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/44101
    reason: "influxdb-client"
    recipe-maintainers:
      - bkreider

  recipe-maintainers:
    - ruben-arts
